const ArtIdSeisUno = () => {
    return(
        <div>
            <h2 className="subtitleArt">¿Por qué se produce un estancamiento en la pérdida de peso?</h2>
            <p style={{ textIndent: '2em' }}>Cuando una persona que intenta perder peso entra en una fase de estabilización, es decir, ya no baja más de peso a pesar de mantener hábitos saludables, se produce un estancamiento en la pérdida de peso. No hay un periodo determinado de duración del mismo y puede variar de 7 a 21 días.</p>
            <p style={{ textIndent: '2em' }}>Durante las primeras semanas de adelgazamiento, la pérdida de peso es rápida debido a la eliminación de agua y masa muscular. Se sabe que el músculo participa de manera importante en el gasto metabólico basal. Esta pérdida de masa muscular implica un descenso del metabolismo, un menor gasto energético, así como un menor consumo de calorías.</p>
            <p style={{ textIndent: '2em' }}>Es decir, cuando las calorías que el metabolismo requiere igualan a las calorías que la persona consume, se produce un estancamiento en el peso. Este equilibrio se alcanza porque el cuerpo se adapta a la reducción de calorías, disminuyendo el gasto energético para mantener el peso.</p>
            <p style={{ textIndent: '2em' }}>Este fenómeno es común durante los procesos de pérdida de peso y es importante tenerlo en cuenta. Para superar el estancamiento, se puede evaluar la necesidad de ajustar la dieta o la rutina de ejercicios, de modo que se vuelva a generar un déficit calórico que permita retomar la pérdida de peso.</p>
            <h2 className="subtitleArt">Consejos para evitar el estancamiento en la pérdida de peso</h2>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '1em'}}><b>1. Establecer un objetivo de pérdida de peso realista:</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>Establecer un objetivo de pérdida de peso realista es fundamental para evitar el estancamiento y mantenerte motivado en tu proceso de transformación. Es importante tomar en cuenta tus características individuales como edad, género, nivel de actividad física y composición corporal para determinar una meta de <a className="linkAbsolute" href="https://www.fitknow.fit/ejercicios-para-perder-grasa">pérdida de peso saludable y alcanzable a mediano plazo</a>.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Muchas veces, las personas se fijan objetivos demasiado ambiciosos, como perder una cantidad exagerada de peso en un período corto de tiempo. Esto luego puede ser frustrante y llevar al desánimo cuando no se logran alcanzar esas metas poco realistas. En su lugar, es mejor establecer objetivos más moderados y alcanzables, que te permitan celebrar cada pequeño logro a lo largo del camino.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Es importante interpretar correctamente los resultados de los estudios de composición corporal, ya que pueden variar según el nivel de hidratación, ejercicio previo, ingesta de alcohol o toma de medicación. Esto te ayudará a tener una visión más clara de cómo está evolucionando tu porcentaje de grasa corporal, más allá de lo que indique simplemente la báscula. Recuerda que el peso por sí solo no es el único indicador de progreso en un plan de pérdida de peso saludable.</p>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '1em'}}><b>2. Revisar la dieta y anotar un registro de los alimentos para evitar el estancamiento en la pérdida de peso:</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>Es importante revisar cuidadosamente tu dieta y llevar un registro detallado de los alimentos que consumes. A menudo, las personas subestiman o pasan por alto la cantidad de alimentos que ingieren, especialmente cuando comen de manera distraída mientras realizan otras actividades como mirar televisión.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Es importante asegurarse de estar midiendo y anotando con precisión las porciones reales de los alimentos que consumes. Es fácil cometer el error de infravalorar la ingesta si no se presta atención a las cantidades. Llevar un registro minucioso de todo lo que comes te ayudará a tener una imagen más clara de tus hábitos alimenticios y a identificar posibles áreas de mejora.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Además, este registro te permitirá analizar patrones y tendencias en tu consumo de alimentos, lo cual puede ser muy revelador. Quizás descubras que hay ciertos momentos del día o situaciones en las que tienes más tendencia a comer de más o a elegir opciones menos saludables. Identificar estos disparadores te dará la oportunidad de implementar estrategias para manejarlos de manera más eficaz.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Aqui te dejamos <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-desayunos-altos-en-proteina">7 Recetas de desayunos altos en proteína</a>, <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-de-almuerzos-altos-en-proteinas">4 recetas de almuerzos altos en proteínas</a> y <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-de-postres-saludable">5 recetas de postres saludables</a></p>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '1em'}}><b>3. Mantener la actividad física  para evitar el estancamiento en la pérdida de peso:</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>Es fundamental mantener una rutina de actividad física balanceada y adaptada a tus objetivos. Si bien los ejercicios cardiovasculares son cruciales para quemar calorías y mejorar la salud cardíaca, es igualmente importante incorporar <a className="linkAbsolute" href="https://www.fitknow.fit/Tips-para-aumentar-masa-muscular">ejercicios de fuerza que ayuden a aumentar tu masa muscular.</a></p>
            <p style={{marginTop: '0', textIndent: '2em'}}>La inclusión de ejercicios de levantamiento de pesas o entrenamiento con resistencia ofrece múltiples beneficios. Estos tipos de ejercicios no solo contribuyen a desarrollar y tonificar la musculatura, sino que también favorecen un mayor gasto calórico, incluso en reposo. Esto se debe a que el músculo es un tejido metabólicamente activo que requiere más energía para su mantenimiento.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Al combinar el cardio con el entrenamiento de fuerza, estarás trabajando de manera integral para alcanzar tus metas de <a className="linkAbsolute" href="https://www.fitknow.fit/ejercicios-para-perder-grasa">pérdida de peso y mejora de la composición corporal</a>. El aumento de la masa muscular te ayudará a quemar más calorías y a mantener un metabolismo más activo a largo plazo, lo cual es fundamental para evitar el temido efecto meseta o estancamiento.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Recuerda que es importante encontrar un balance y una combinación de actividades que te resulten agradables y sostenibles. Esto te ayudará a mantener la motivación y a incorporar el ejercicio como parte integral de tu estilo de vida saludable.</p>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '1em'}}><b>4. Valorar los resultados conseguidos:</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>A menudo, pequeñas reducciones en el peso corporal pueden traer consigo grandes beneficios para la salud. Por ejemplo, reducir tan solo 1 kilogramo de peso supone disminuir aproximadamente 4 kilogramos de presión sobre las articulaciones de las rodillas. Esto puede significar una notable mejoría en problemas de dolor o desgaste articular.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Más allá de los cambios en el peso, es importante monitorizar otros indicadores de salud, como niveles de colesterol, presión arterial, glucosa en sangre, e incluso síntomas de condiciones asociadas al exceso de peso, como diabetes o problemas cardiovasculares. Estos cambios positivos en los marcadores de salud pueden ser igual o más significativos que la reducción numérica en la báscula.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Estar atento a estos pequeños pero significativos avances te ayudará a mantener la motivación y a valorar el progreso de manera más integral. Recuerda que una pérdida de peso saludable y sostenible no se trata solo de un número, sino de los beneficios concretos que puedes experimentar en tu salud y bienestar general.</p>

        </div>
    )
}

export default ArtIdSeisUno