const ArtIdNueveUno = () => {
    return(
        <div>
            <h2 className="subtitleArt">Importancia del ejercicio durante el embarazo</h2>
            <p style={{ textIndent: '2em' }}>La práctica regular de <a className="linkAbsolute" href="https://www.fitknow.fit/beneficios-del-ejercicio-durante-el-embarazo">ejercicio durante el embarazo ofrece una serie de beneficios importantes</a> tanto para la salud de la madre como para el desarrollo del bebé. En primer lugar, el ejercicio ayuda a mantener un peso saludable y a prevenir el aumento excesivo de peso, lo cual reduce el riesgo de complicaciones como diabetes gestacional e hipertensión. Además, fortalece los músculos y mejora la resistencia, preparando el cuerpo de la mujer para el esfuerzo físico del parto.</p>
            <p style={{ textIndent: '2em' }}>Asimismo, el ejercicio contribuye a mejorar la circulación sanguínea y la oxigenación, lo que favorece un adecuado desarrollo fetal. Por otro lado, ayuda a reducir el estrés y la ansiedad, dos factores que pueden afectar negativamente el embarazo. Las mujeres que mantienen una rutina de ejercicio suelen experimentar un mejor estado de ánimo, con menores niveles de depresión y fatiga.</p>
            <p style={{ textIndent: '2em' }}>Más aún, el ejercicio prenatal puede facilitar una recuperación más rápida después del parto, ya que los músculos y la condición física de la madre se encuentran en mejor estado. Esto se traduce en una menor probabilidad de sufrir dolores de espalda, incontinencia urinaria y otros problemas comunes en el postparto.</p>
            <h2 className="subtitleArt">Ejercicios recomendados durante el embarazo</h2>
            <p style={{ textIndent: '2em' }}>Mantenerse activa durante el embarazo es crucial, pero es importante elegir ejercicios que se adapten a los cambios físicos y las necesidades de cada etapa. Una gran opción es la natación o el aquagym, ya que la sensación de flotabilidad y ligereza en el agua puede resultar muy placentera. Otra alternativa es el baile, una actividad divertida que ayuda a mantenerse en movimiento.</p>
            <p style={{ textIndent: '2em' }}>Para quienes prefieren actividades más tradicionales, <a className="linkAbsolute" href="https://www.fitknow.fit/beneficios-del-yoga">el yoga</a> y el pilates ofrecen una combinación ideal de fortalecimiento, flexibilidad y técnicas de respiración. Asimismo, el ciclismo, ya sea en bicicleta estática o en el exterior, es una excelente opción cardiovascular. Y no podemos olvidar la siempre recomendada caminata, que permite ajustar el ritmo, la distancia y la inclinación según las preferencias y capacidades de cada mujer.</p>
            <p style={{ textIndent: '2em' }}>Si antes del embarazo disfrutaba de correr, es probable que pueda continuar haciéndolo, aunque quizás deba adaptar su rutina. Lo importante es comenzar de forma moderada, dedicando los primeros y últimos minutos a un calentamiento y enfriamiento suaves, y evitar ejercicios que impliquen saltos o riesgo de caídas. Escuchar al cuerpo y consultar con el médico son claves para asegurar que la actividad física durante el embarazo sea segura y beneficiosa</p>
            <h2 className="subtitleArt">Ejercicios que debe evitar durante el embarazo</h2>
            <p style={{ textIndent: '2em' }}>Durante el embarazo, existen ciertos ejercicios que se deben evitar por razones de seguridad. La mayoría de los médicos recomiendan que las mujeres embarazadas eviten aquellos ejercicios que requieran acostarse boca arriba más allá del primer trimestre, ya que esto puede afectar la circulación sanguínea.</p>
            <p style={{ textIndent: '2em' }}>Además, a menos que su médico le indique lo contrario, también se aconseja evitar actividades que impliquen rebotar, saltar, cambiar bruscamente de dirección o que conlleven un riesgo de lesionar la zona abdominal. Por este motivo, se suele recomendar evitar los deportes de contacto, el esquí alpino, el patinaje, la gimnasia y la equitación, debido a su mayor riesgo de lesiones.</p>
            <p style={{ textIndent: '2em' }}>En cuanto al aeróbic con step (escalón), algunos médicos lo consideran aceptable siempre y cuando se vaya reduciendo la altura del escalón a medida que avance el embarazo, ya que el cambio en el centro de gravedad de la embarazada aumenta las probabilidades de caídas. Sin embargo, otros profesionales indican que es mejor evitar esta actividad. Si decide realizar aeróbic, es importante asegurarse de no quedarse sin aliento ni llegar a estar completamente agotada.</p>
            <h2 className="subtitleArt">Consejos para las mujeres embarazadas que desean realizar actividad física</h2>
            <p style={{ textIndent: '2em' }}>Para las mujeres embarazadas que desean mantener una rutina de ejercicios, es importante tomar en cuenta algunas recomendaciones clave. En primer lugar, es esencial consultar con el médico o el especialista en salud prenatal antes de iniciar o modificar cualquier programa de actividad física. Ellos podrán evaluar el estado de salud de la mujer y dar las indicaciones adecuadas según cada etapa del embarazo.</p>
            <p style={{ textIndent: '2em' }}>Una vez que se cuente con la aprobación médica, es importante empezar de manera gradual y mantener una intensidad moderada. Las embarazadas deben evitar los ejercicios de alto impacto o los que impliquen riesgo de caída o golpes. En su lugar, se recomiendan actividades como caminatas, natación, yoga prenatal y ejercicios de fortalecimiento muscular con bajo impacto.</p>
            <p style={{ textIndent: '2em' }}>Asimismo, es crucial prestar atención a las señales del cuerpo y no ejercitarse hasta el agotamiento. Es normal que la fatiga y la falta de energía sean más frecuentes durante el embarazo, por lo que la mujer debe estar dispuesta a ajustar la duración y la intensidad de los entrenamientos según su comodidad y tolerancia.</p>
            <p style={{ textIndent: '2em' }}>Otra recomendación importante es <a className="linkAbsolute" href="https://www.fitknow.fit/cuanta-agua-beber-cada-dia">mantenerse bien hidratada antes</a>, durante y después de los ejercicios, y evitar ejercitarse en ambientes muy calurosos o húmedos, ya que esto puede generar deshidratación o sobrecalentamiento. Además, se sugiere usar ropa holgada y cómoda que facilite los movimientos.</p>
            <h2 className="subtitleArt">Idea de rutina de ejercicios para mujeres embarazadas</h2>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '1em'}}><b>1. Calentamiento (10-15 minutos):</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>El calentamiento es una parte esencial de la rutina, con una duración de 10 a 15 minutos. Durante esta etapa, se recomienda comenzar con una caminata lenta, seguida de movimientos suaves de rotación en tobillos, rodillas y cadera. Además, se pueden incluir pequeños ejercicios de estiramiento enfocados en brazos, piernas y espalda. Este calentamiento ayuda a preparar el cuerpo para la actividad física y reduce el riesgo de lesiones.</p>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '1em'}}><b>2. Ejercicios aeróbicos (20-30 minutos):</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>Después del calentamiento, la mujer embarazada puede pasar a la fase aeróbica de la rutina, que suele durar entre 20 y 30 minutos. Durante este tiempo, se pueden realizar actividades como caminata rápida, trote suave (si lo tolera), natación o ejercicios en el agua, que son muy recomendados debido al bajo impacto, y baile o rutinas de ejercicios de bajo impacto. Estas actividades ayudan a mejorar la resistencia cardiovascular y la circulación.</p>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '1em'}}><b>3. Fortalecimiento muscular (15-20 minutos):</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>La siguiente etapa se enfoca en el fortalecimiento muscular, con una duración de 15 a 20 minutos. Aquí se pueden incluir ejercicios de resistencia con bandas elásticas o pesas ligeras para trabajar brazos, piernas y espalda. También se recomienda hacer ejercicios de Kegel para fortalecer el piso pélvico y ejercicios de estabilización del core, evitando los abdominales tradicionales.</p>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '1em'}}><b>4. Enfriamiento y estiramiento (10-15 minutos):</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>Finalmente, la rutina termina con una fase de enfriamiento y estiramiento de 10 a 15 minutos. Durante esta etapa, se realizan estiramientos suaves y progresivos de las principales áreas musculares, acompañados de respiraciones profundas y técnicas de relajación.</p>
            <p style={{marginTop: '4em', textIndent: '2em'}}>Es importante que la embarazada escuche las señales de su cuerpo y ajuste la intensidad y duración de los ejercicios según su nivel de energía y comodidad. Idealmente, realizar esta rutina de 3 a 5 veces por semana, con días de descanso entre sesiones.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Siempre es recomendable consultar con el médico o el especialista en ejercicio prenatal para asegurarse de que la rutina es segura y apropiada para cada etapa del embarazo. El objetivo es mantener una actividad física regular, pero sin excederse.</p>
        </div>
    )
}

export default ArtIdNueveUno