const ArtIdOcho = () => {
    return(
        <div>
            <h2 className="subtitleArt">1. El deporte favorece el crecimiento físico y mental de los niños</h2>
            <p style={{ textIndent: '2em' }}>La práctica regular de deporte y actividad física desempeña un papel fundamental en el desarrollo integral de los niños, tanto a nivel físico como mental y emocional. Desde el punto de vista físico, el deporte estimula el crecimiento y fortalecimiento de diferentes estructuras y sistemas del organismo infantil. Esto se traduce en mejoras concretas en capacidades como la percepción espacial, la coordinación motora, la agilidad y el equilibrio. Los niños que participan de manera constante en actividades deportivas desarrollan una mejor conciencia de los límites y capacidades de su cuerpo, lo que a su vez fomenta el autocontrol y la humildad.</p>
            <p style={{ textIndent: '2em' }}>Pero los beneficios del deporte en los niños van más allá de lo puramente físico. También contribuye de manera significativa a su desarrollo mental y emocional. A través de la práctica deportiva, los niños aprenden a superar retos, a trabajar en equipo, a gestionar la frustración y a desarrollar una mentalidad de crecimiento. Esto les ayuda a construir una imagen más sólida y realista de sí mismos, lo que es fundamental para su bienestar psicológico.</p>
            <p style={{ textIndent: '2em' }}>Además, el deporte infantil promueve la liberación de endorfinas y la regulación de neurotransmisores cerebrales, lo que genera sensaciones de bienestar, confianza y alegría. Esto no solo contribuye a la salud mental de los niños, sino que también les ayuda a desarrollar habilidades sociales y de liderazgo.</p>
            <h2 className="subtitleArt">2. El deporte potencia la creación de hábitos en los niños</h2>
            <p style={{ textIndent: '2em' }}>La práctica de deporte también juega un papel fundamental en la adopción de hábitos de vida saludables en los niños.</p>
            <p style={{ textIndent: '2em' }}>Cuando los niños se involucran regularmente en actividades deportivas, se crea en ellos una predisposición natural hacia la adopción de hábitos que favorecen su bienestar integral. Esto se debe a que el deporte los motiva a cuidar su cuerpo y su salud de manera más consciente.</p>
            <p style={{ textIndent: '2em' }}>Al comprometerse con una rutina de ejercicio, los niños tienden a acompañar esta práctica con una alimentación más equilibrada y nutritiva. Asimismo, desarrollan una mayor atención a la higiene personal, como el lavado de manos, el cepillado de dientes y otras prácticas de cuidado corporal.</p>
            <p style={{ textIndent: '2em' }}>Además, la disciplina que requiere el deporte también se transfiere a una mejor gestión de las tareas y actividades diarias de los niños. Aprender a organizar los horarios, cumplir con rutinas y establecer prioridades les ayuda a desarrollar habilidades de planificación y autocontrol que les serán de gran utilidad a lo largo de su vida.</p>
            <h2 className="subtitleArt">3. El deporte ayuda a superar la timidez y potencia las habilidades sociales en los niños</h2>
            <p style={{ textIndent: '2em' }}>La práctica de deporte, especialmente en entornos grupales, también desempeña un papel clave en el desarrollo de las habilidades sociales y la superación de la timidez en los niños.</p>
            <p style={{ textIndent: '2em' }}>Cuando los niños participan en actividades deportivas, se ven inmersos en un entorno social que les ofrece la oportunidad de interactuar, comunicarse y trabajar en equipo con otros compañeros. Esto les ayuda a desarrollar importantes capacidades sociales, como el liderazgo, la cohesión grupal y la comunicación efectiva.</p>
            <p style={{ textIndent: '2em' }}>Especialmente para aquellos niños que puedan presentar mayor timidez o dificultades para relacionarse, el deporte les brinda un espacio seguro y estructurado para superar estas barreras. A través de la práctica deportiva, aprenden a expresarse, a escuchar a los demás y a encontrar su lugar dentro de un grupo.</p>
            <p style={{ textIndent: '2em' }}>Además, el deporte enseña a los niños a respetar reglas, a aceptar la diversidad de personalidades y a desarrollar empatía hacia sus compañeros. Estas habilidades sociales y emocionales les serán de gran utilidad a lo largo de su vida, tanto en el ámbito escolar como en sus futuras relaciones personales y profesionales.</p>
            <h2 className="subtitleArt">4. El deporte ayuda a reducir el estrés y mejora el rendimiento académico en los niños</h2>
            <p style={{ textIndent: '2em' }}>La práctica regular de actividad física se ha demostrado que está relacionada con una mayor capacidad de concentración y un mejor desempeño en el ámbito escolar. Esto se debe a que el deporte juega un papel fundamental en la liberación de tensiones y la mejora del estado de ánimo de los niños.</p>
            <p style={{ textIndent: '2em' }}>Cuando los niños se involucran en actividades deportivas, tienen la oportunidad de liberar la energía y el estrés acumulados, lo cual les ayuda a combatir problemas como la ansiedad o la depresión. Al sentirse más relajados y con una mejor perspectiva emocional, pueden enfocar mejor su atención en las tareas académicas y mejorar su rendimiento general en la escuela.</p>
            <p style={{ textIndent: '2em' }}>Además, el deporte estimula la producción de endorfinas, las "hormonas de la felicidad", lo cual contribuye a elevar el estado de ánimo y promover un mayor bienestar mental. Esto se traduce en un mayor nivel de motivación y una actitud más positiva hacia el aprendizaje y el desempeño escolar.</p>
            <h2 className="subtitleArt">5. El deporte aumenta la autoestima en los niños</h2>
            <p style={{ textIndent: '2em' }}>Cuando los más jóvenes superan retos y desafíos en el ámbito deportivo, adquieren una mayor sensación de seguridad y capacidad para afrontar nuevos desafíos. El reconocimiento de su esfuerzo y trabajo bien hecho aumenta su confianza en sí mismos, fortaleciendo su autoestima. Asimismo, el deporte les permite desarrollar un sentido de logro y dominio personal que se traduce en un mejor autoconcepto. Todo ello contribuye a que los niños y niñas se sientan más seguros y empoderados, lo que sin duda tendrá un impacto positivo en todas las áreas de su vida.</p>
            <h2 className="subtitleArt">6. El deporte evita el sedentarismo en los niños</h2>
            <p style={{ textIndent: '2em' }}>El ocio deportivo fomenta un estilo de vida activo y saludable, evitando el exceso de tiempo dedicado a actividades sedentarias y pasivas. Esto no solo tiene un impacto positivo en la salud física, sino que también contribuye a la salud mental y el bienestar general de los más jóvenes. Además, la actividad física regular reduce los riesgos asociados con el sedentarismo, como el sobrepeso, la obesidad y las enfermedades cardiovasculares. De esta manera, el deporte se convierte en una herramienta clave para promover hábitos saludables desde la infancia.</p>
            <h2 className="subtitleArt">7. El deporte enseña a los niños a trabajar en equipo</h2>
            <p style={{ textIndent: '2em' }}>Cuando los niños participan en actividades deportivas grupales, se ven inmersos en un entorno que les exige comunicarse, coordinarse y trabajar de manera conjunta para lograr objetivos comunes. Esto les brinda valiosas oportunidades para desarrollar habilidades sociales y de trabajo en equipo.</p>
            <p style={{ textIndent: '2em' }}>A través de la práctica deportiva, los niños aprenden a escuchar a sus compañeros, a respetar diferentes roles y responsabilidades, y a anteponer los intereses del equipo a los suyos personales. Desarrollan una mayor capacidad de comunicación, negociación y resolución de conflictos, habilidades que serán fundamentales a lo largo de su vida, tanto en el ámbito escolar como en sus futuras relaciones personales y profesionales.</p>
            <p style={{ textIndent: '2em' }}>Además, el deporte de equipo fomenta el respeto y la tolerancia hacia la diversidad de personalidades y habilidades de los miembros del grupo. Los niños aprenden a valorar las fortalezas de cada uno y a complementarse mutuamente para lograr mejores resultados.</p>
        </div>
    )
}

export default ArtIdOcho