const ArtIdDiecisiete = () => {

    return(
        <div>
            <h2 className="subtitleArt">1. Alimentos antiinflamatorios y saludables: Pescados Azules:</h2>
            <p style={{ textIndent: '2em' }}>Los pescados azules son una excelente opción para incluir en una dieta antiinflamatoria y saludable. Estos peces son ricos en ácidos grasos Omega 3, unos ácidos grasos esenciales que tienen propiedades antiinflamatorias.</p>
            <p style={{ textIndent: '2em' }}>Además, los pescados azules son una fuente importante de vitaminas B, como la vitamina B12, que juegan un papel clave en el metabolismo y la producción de energía. También contienen vitamina D, <a className="linkAbsolute" href="https://www.fitknow.fit/aumentar-la-hemoglobina">un nutriente vital para el sistema inmunológico</a> y la salud ósea.</p>
            <p style={{ textIndent: '2em' }}>Otra característica destacada de los pescados azules es su aporte de fósforo, un mineral esencial para el funcionamiento adecuado de los riñones y los huesos. Finalmente, estos peces son una excelente fuente de proteínas de alto valor biológico, lo que significa que contienen todos los aminoácidos esenciales que nuestro cuerpo necesita.</p>
            <h2 className="subtitleArt">2.  Alimentos antiinflamatorios y saludables: Brócoli y Otras Crucíferas:</h2>
            <p style={{ textIndent: '2em' }}>Las crucíferas, como el brócoli, son un grupo de alimentos muy beneficiosos para una dieta antiinflamatoria y saludable.</p>
            <p style={{ textIndent: '2em' }}>Estas verduras se destacan por su contenido de glucosinolatos, que son compuestos bioactivos con propiedades antiinflamatorias y antioxidantes. Particularmente, el brócoli es rico en un glucosinolato llamado sulforafano, el cual ha demostrado ser muy eficaz en la reducción de la inflamación a nivel celular.</p>
            <p style={{ textIndent: '2em' }}>Los glucosinolatos del brócoli y otras crucíferas, como la coliflor, el repollo y la col rizada, actúan de manera múltiple para combatir la inflamación. Por un lado, ayudan a neutralizar los radicales libres y especies reactivas de oxígeno, que pueden causar daño a las células. Esto se traduce en una menor carga inflamatoria en el organismo. Por otro lado, los glucosinolatos modulan la actividad de ciertas vías de señalización celular que están implicadas en la respuesta inflamatoria.</p>
            <p style={{ textIndent: '2em' }}>Además de sus propiedades antiinflamatorias, las crucíferas son ricas en fibra, vitaminas, minerales y otros fitoquímicos beneficiosos para la salud en general. Por ejemplo, son buenas fuentes de vitamina C, vitamina K, folato y potasio, entre otros nutrientes esenciales</p>
            <h2 className="subtitleArt">3.  Alimentos antiinflamatorios y saludables: Té Verde:</h2>
            <p style={{ textIndent: '2em' }}>El té verde es otro alimento que destaca por sus propiedades antiinflamatorias y saludables.Este tipo de té es rico en compuestos llamados polifenoles, especialmente las epigalocatequinas, que son moléculas con una gran capacidad antioxidante y antiinflamatoria. Estos polifenoles del té verde pueden neutralizar los radicales libres y reducir la inflamación a nivel celular, lo cual los convierte en aliados clave para la salud.</p>
            <p style={{ textIndent: '2em' }}>Los estudios han demostrado que consumir regularmente té verde, al menos 3 tazas al día, puede tener efectos beneficiosos en diversas condiciones inflamatorias, como enfermedades del corazón, diabetes, cáncer y problemas del cerebro. Esto se debe a que los polifenoles del té verde ayudan a regular los procesos celulares que están relacionados con la inflamación.</p>
            <p style={{ textIndent: '2em' }}>Además, se puede potenciar aún más el efecto antiinflamatorio del té verde al combinarlo con jengibre. El jengibre también contiene compuestos beneficiosos, como los gingeroles, que poseen propiedades antiinflamatorias y antioxidantes que se complementan bien con las del té verde.</p>
            <h2 className="subtitleArt">4.  Alimentos antiinflamatorios y saludables: Cúrcuma:</h2>
            <p style={{ textIndent: '2em' }}>La cúrcuma es otro alimento que destaca por sus extraordinarias propiedades antiinflamatorias y saludables.</p>
            <p style={{ textIndent: '2em' }}>Esta especia, que viene de la India, es rica en una sustancia llamada curcumina, que es la responsable de la mayoría de sus beneficios para la salud. La curcumina es un poderoso antioxidante y antiinflamatorio que ha demostrado ser muy eficaz para reducir la inflamación a nivel celular.</p>
            <p style={{ textIndent: '2em' }}>Los estudios han mostrado que la curcumina puede regular diversos procesos celulares relacionados con la inflamación. Además, puede neutralizar los radicales libres y las sustancias reactivas de oxígeno, lo cual ayuda a disminuir el estrés y, por lo tanto, la carga inflamatoria en el cuerpo.</p>
            <p style={{ textIndent: '2em' }}>Una característica importante de la curcumina es que se absorbe mejor cuando se consume con ciertos alimentos. Por ejemplo, se ha visto que se absorbe mejor cuando se toma con aceite de oliva, aguacate o pimienta negra.</p>
            <p style={{ textIndent: '2em' }}>El aceite de oliva y el aguacate aportan grasas saludables que facilitan la absorción de la curcumina, mientras que la pimienta negra contiene una sustancia llamada piperina que también mejora la biodisponibilidad de este poderoso antioxidante y antiinflamatorio.</p>
            <h2 className="subtitleArt">5.  Alimentos antiinflamatorios y saludables: Frutos Rojos:</h2>
            <p style={{ textIndent: '2em' }}>Los frutos rojos, como las fresas, los arándanos, las frambuesas y las moras, son otro grupo de alimentos que se destacan por sus propiedades antiinflamatorias y saludables. Estos pequeños y coloridos frutos son ricos en sustancias llamadas polifenoles, como las antocianinas y los flavonoides, que tienen un fuerte efecto antioxidante y antiinflamatorio a nivel celular.</p>
            <p style={{ textIndent: '2em' }}>Los estudios han demostrado que comer frutos rojos con regularidad puede ayudar a reducir la inflamación y el estrés en el cuerpo. Esto se debe a que los polifenoles presentes en estos frutos pueden neutralizar los radicales libres y regular los procesos celulares relacionados con la inflamación.</p>
            <p style={{ textIndent: '2em' }}>Además de sus propiedades antiinflamatorias, los frutos rojos son una excelente fuente de otros nutrientes beneficiosos para la salud, como fibra, vitamina C, ácido fólico, manganeso y potasio.</p>
            <p style={{ textIndent: '2em' }}>Incorporar una variedad de frutos rojos en la dieta, como fresas, arándanos, frambuesas y moras, puede ser una estrategia efectiva para aprovechar los efectos antiinflamatorios y antioxidantes de estos alimentos. Comerlos con regularidad puede contribuir a prevenir y manejar diferentes enfermedades crónicas relacionadas con la inflamación.</p>
            <h2 className="subtitleArt">6.  Alimentos antiinflamatorios y saludables: Jengibre:</h2>
            <p style={{ textIndent: '2em' }}>El jengibre es otra comida que se destaca por sus propiedades antiinflamatorias y beneficios para la salud. Esta raíz, que viene de Asia, tiene compuestos llamados gingeroles que le dan la mayoría de sus efectos saludables. Los gingeroles del jengibre han mostrado tener un fuerte efecto antiinflamatorio, lo que los convierte en aliados clave para combatir la inflamación a nivel celular.</p>
            <p style={{ textIndent: '2em' }}>Los estudios han mostrado que los gingeroles del jengibre pueden ayudar a reducir la liberación de sustancias que causan inflamación, como las prostaglandinas y los leucotrienos. Estas sustancias inflamatorias están involucradas en diferentes procesos fisiológicos y enfermedades, y su exceso puede contribuir al desarrollo de enfermedades crónicas relacionadas con la inflamación.</p>
            <p style={{ textIndent: '2em' }}>Además de sus propiedades antiinflamatorias, el jengibre también tiene efectos antioxidantes, lo que le permite neutralizar los radicales libres y reducir el estrés oxidativo en el cuerpo. Esto, a su vez, contribuye a disminuir la carga inflamatoria general.</p>
            <p style={{ textIndent: '2em' }}>Incorporar una variedad de frutos rojos en la dieta, como fresas, arándanos, frambuesas y moras, puede ser una estrategia efectiva para aprovechar los efectos antiinflamatorios y antioxidantes de estos alimentos. Comerlos con regularidad puede contribuir a prevenir y manejar diferentes enfermedades crónicas relacionadas con la inflamación.</p>
            <h2 className="subtitleArt">7.  Alimentos antiinflamatorios y saludables: Aceite de Oliva Virgen Extra:</h2>
            <p style={{ textIndent: '2em' }}>El aceite de oliva virgen extra es otro alimento que se destaca por sus propiedades antiinflamatorias y los beneficios que tiene para la salud. Este valioso aceite se obtiene directamente de las aceitunas usando métodos mecánicos, y contiene una sustancia llamada oleocanthal, que tiene propiedades antioxidantes y antiinflamatorias similares al medicamento ibuprofeno.</p>
            <p style={{ textIndent: '2em' }}>Los estudios científicos han demostrado que el oleocanthal en el aceite de oliva virgen extra puede ayudar a reducir la inflamación a nivel celular. Esta sustancia puede bloquear la acción de ciertas enzimas que causan inflamación, de manera parecida a como lo hace el ibuprofeno.</p>
            <p style={{ textIndent: '2em' }}>Además de sus efectos antiinflamatorios, el aceite de oliva virgen extra también es rico en ácidos grasos saludables, como el ácido oleico, y en compuestos fenólicos con propiedades antioxidantes, que ayudan a reducir el estrés oxidativo.</p>
            <p style={{ textIndent: '2em' }}>Incluir el aceite de oliva virgen extra en la dieta, ya sea para cocinar, aderezar ensaladas o consumirlo crudo, puede ser una excelente manera de aprovechar sus beneficios antiinflamatorios y mejorar la salud en general. Consumirlo regularmente puede ser una herramienta valiosa para prevenir y manejar diferentes enfermedades relacionadas con la inflamación crónica.</p>
            <h2 className="subtitleArt">8.  Alimentos antiinflamatorios y saludables: Remolacha:</h2>
            <p style={{ textIndent: '2em' }}>La remolacha es otro alimento que se destaca por sus propiedades antiinflamatorias y múltiples beneficios para la salud.</p>
            <p style={{ textIndent: '2em' }}>Esta raíz de color rojo intenso es una excelente fuente de diversos nutrientes y compuestos que le dan propiedades antiinflamatorias y antioxidantes.</p>
            <p style={{ textIndent: '2em' }}>Por un lado, la remolacha es rica en fibra, que ayuda a regular el sistema digestivo y reduce la inflamación intestinal. También contiene importantes cantidades de ácido fólico y vitamina C, nutrientes esenciales para el buen funcionamiento del organismo.</p>
            <p style={{ textIndent: '2em' }}>Pero uno de los principales responsables de las propiedades antiinflamatorias de la remolacha son las betalaínas, que son los pigmentos naturales que le dan su característico color rojo. Estas moléculas tienen una potente actividad antioxidante y antiinflamatoria, lo que las convierte en aliadas efectivas para combatir el estrés oxidativo y la inflamación a nivel celular.</p>
            <p style={{ textIndent: '2em' }}>Diversos estudios han demostrado que el consumo de remolacha puede ayudar a reducir los marcadores de inflamación, como la proteína C reactiva y las citoquinas pro-inflamatorias. Esto se debe a que las betalaínas de la remolacha pueden modular los procesos relacionados con la respuesta inflamatoria.</p>
            <p style={{ textIndent: '2em' }}>Incluir la remolacha en la dieta, ya sea en ensaladas, jugos, sopas o platos de cocina, puede ser una excelente forma de aprovechar sus beneficios antiinflamatorios y nutricionales. Consumirla regularmente puede contribuir a la prevención y el manejo de diversas enfermedades asociadas a la inflamación crónica.</p>
            <h2 className="subtitleArt">9.  Alimentos antiinflamatorios y saludables: Pimientos:</h2>
            <p style={{ textIndent: '2em' }}>Los pimientos, con su diversidad de variedades y colores, también son alimentos con propiedades antiinflamatorias y beneficios para la salud.</p>
            <p style={{ textIndent: '2em' }}>Estos vegetales son una excelente fuente de varios nutrientes y sustancias activas que les dan sus características antiinflamatorias y analgésicas (que reducen el dolor).</p>
            <p style={{ textIndent: '2em' }}>Por un lado, los pimientos son una buena fuente de vitamina B6 y ácido fólico, dos nutrientes esenciales para el buen funcionamiento del sistema inmunológico y la reducción de la inflamación.</p>
            <p style={{ textIndent: '2em' }}>Además, los pimientos contienen muchos flavonoides, que son compuestos vegetales con potentes efectos antioxidantes y antiinflamatorios. Estos flavonoides pueden ayudar a regular los procesos celulares relacionados con la respuesta inflamatoria.</p>
            <p style={{ textIndent: '2em' }}>Asimismo, los pimientos tienen salicilatos, que son moléculas con propiedades analgésicas y antiinflamatorias similares a las de la aspirina. Estos salicilatos pueden contribuir a disminuir el dolor y la inflamación en el cuerpo.</p>
            <p style={{ textIndent: '2em' }}>Estudios científicos han demostrado que comer pimientos regularmente puede ayudar a reducir los niveles de marcadores inflamatorios, como la proteína C reactiva y las citoquinas pro-inflamatorias. Esto se debe a la combinación de los nutrientes y sustancias activas presentes en estos vegetales.</p>
            <p style={{ textIndent: '2em' }}>Incorporar los pimientos a la dieta, ya sea en ensaladas, guisos, salsas o crudos, puede ser una excelente forma de aprovechar sus beneficios antiinflamatorios y promover la salud en general. Consumirlos regularmente puede contribuir a prevenir y manejar diversas afecciones relacionadas con la inflamación.</p>
            <h2 className="subtitleArt">10.  Alimentos antiinflamatorios y saludables: Ajo y Cebolla:</h2>
            <p style={{ textIndent: '2em' }}>El ajo y la cebolla son dos alimentos que se destacan por tener propiedades antiinflamatorias y ser beneficiosos para la salud.</p>        
            <p style={{ textIndent: '2em' }}>Estos dos vegetales de la familia de las Alliáceas son considerados potentes antiinflamatorios naturales gracias a que contienen sustancias activas como la aliína, la quercetina y la alicina.</p>        
            <p style={{ textIndent: '2em' }}>La aliína es un compuesto con azufre presente tanto en el ajo como en la cebolla. Tiene fuertes propiedades antioxidantes y antiinflamatorias. Los estudios han demostrado que la aliína puede ayudar a bloquear la actividad de enzimas pro-inflamatorias, de una manera similar a como lo hacen algunos medicamentos antiinflamatorios.</p>        
            <p style={{ textIndent: '2em' }}>Por otro lado, la quercetina es un flavonoide abundante en la cebolla que también ha mostrado tener propiedades antiinflamatorias. Esta molécula puede regular la expresión de genes involucrados en la respuesta inflamatoria, reduciendo así los niveles de sustancias pro-inflamatorias.</p>        
            <p style={{ textIndent: '2em' }}>Además, la alicina es un compuesto con azufre que se libera cuando se corta o muele el ajo. Esta sustancia puede inhibir la actividad de enzimas como la lipooxigenasa, lo que se traduce en una disminución de la inflamación a nivel celular.</p>        
            <p style={{ textIndent: '2em' }}>Tanto el ajo como la cebolla son ingredientes versátiles que se pueden incorporar fácilmente a la dieta, ya sea como condimentos, en salsas, sopas o platos de cocina. Consumirlos regularmente puede ser una estrategia efectiva para aprovechar sus beneficios antiinflamatorios y promover la salud en general.</p>        

        </div>
    )

}

export default ArtIdDiecisiete

