const ArtIdUno = () =>{
    return(
        <div>
           <h2 className="subtitleArt">Así debe ser tu entrenamiento para aumentar masa muscular en Piernas y Glúteos</h2>
           <p style={{ textIndent: '2em' }}>Si tu objetivo es aumentar la masa muscular de tus piernas y glúteos, es fundamental que realices un programa de ejercicio especializado para estos grupos musculares. Algunos de las recomendaciones son:</p>
           <ul>
                <li style={{ textIndent: '0' }}><strong>Ejercicios compuestos:</strong> Enfócate en ejercicios que involucren múltiples articulaciones y grandes grupos musculares, como sentadillas, zancadas, hip thrusts y peso muerto. Estos ejercicios activan simultáneamente los músculos de las piernas y los glúteos, estimulando un mayor crecimiento.</li>
                <li style={{ textIndent: '0' }}><strong>Variedad de ángulos y amplitudes:</strong> Incorpora variaciones en los ejercicios, como sentadillas de diferentes anchuras de pies, zancadas adelante y atrás, diferentes alturas de hip thrusts, etc. Esto asegura que estimula todas las fibras musculaIncrementa res de las piernas y glúteos.</li>
                <li style={{ textIndent: '0' }}><strong>Volumen y frecuencia:</strong> Aumenta gradualmente el volumen de entrenamiento (series y repeticiones) para las piernas y glúteos. Entrena estos grupos musculares al menos 2-3 veces por semana para promover un crecimiento óptimo.</li>
                <li style={{ textIndent: '0' }}><strong>Progresión de cargas:</strong> El peso, la resistencia o el número de repeticiones en cada sesión para continuar desafiando a los músculos. Esto estimula un crecimiento muscular constante en piernas y glúteos.</li>
                <li style={{ textIndent: '0' }}><strong>Recuperación adecuada:</strong> Asegúrate de brindar suficiente tiempo de recuperación entre sesiones de piernas y glúteos. Esto permite que los músculos se reparen y crezcan.</li>
           </ul>
           <p style={{ textIndent: '2em' }}>Si quieres saber mas consejos para aumentar masa muscular te invitamos a leer: <a className="linkAbsolute" href="https://www.fitknow.fit/Tips-para-aumentar-masa-muscular">6 tips claves para aumentar masa muscular rapidamente</a></p>
           <h2 className="subtitleArt">Calentamiento: importancia del calentamiento antes del entrenamiento</h2>
           <p style={{ textIndent: '2em' }}>Antes de iniciar el entrenamiento, es importante dedicar tiempo al calentamiento. El calentamiento ayuda a activar los músculos, aumentar la circulación sanguínea y reducir el riesgo de lesiones.</p>
           <p style={{ textIndent: '2em' }}>Una de las partes más importantes de las actividades físicas es el calentamiento, ya que es fundamental para evitar lesiones y para que los músculos desarrollen su máximo potencial. Al calentar, estamos preparando nuestro cuerpo de forma progresiva para que pueda realizar una actividad física intensa en las mejores condiciones. </p>
           <p style={{ textIndent: '2em' }}>Dedicar unos minutos a un calentamiento adecuado antes de comenzar el entrenamiento permite que nuestros músculos, tendones y articulaciones se preparen gradualmente para el esfuerzo. Esto ayuda a mejorar el rendimiento, maximizar los beneficios del entrenamiento y, lo más importante, prevenir posibles lesiones que podrían interrumpir nuestro progreso. No descuides este paso previo, pues un buen calentamiento es la mejor forma de cuidar tu salud y potenciar tus resultados.</p>
           <h2 className="subtitleArt">Progresión Gradual de las cargas en el entrenamiento</h2>
           <p style={{ textIndent: '2em' }}>La progresión gradual de las cargas en el entrenamiento es un principio fundamental para lograr resultados efectivos y a largo plazo. Consiste en aumentar de manera paulatina y controlada la intensidad, el volumen y la dificultad de los ejercicios a medida que el cuerpo se adapta a los estímulos.</p>
           <p style={{ textIndent: '2em' }}>Esto es crucial porque permite que nuestro organismo se acostumbre a los estímulos de manera segura y progresiva, evitando lesiones y optimizando los resultados. Algunos de los beneficios clave de una progresión gradual son:</p>
           <ul>
            <li style={{ textIndent: '0' }}><strong>Adaptación progresiva:</strong> Al aumentar las cargas de forma gradual, damos tiempo a que los músculos, tendones, huesos y sistema cardiovascular se adapten de manera adecuada a los mayores desafíos.</li>
            <li style={{ textIndent: '0' }}><strong>Prevención de lesiones:</strong> Los aumentos bruscos de carga pueden sobrecargar las estructuras y generar lesiones. La progresión gradual reduce significativamente este riesgo.</li>
            <li style={{ textIndent: '0' }}><strong>Mejora continua:</strong> A Al ir incrementando poco a poco las cargas, logramos avances sostenidos en fuerza, resistencia, potencia y demás capacidades físicas.</li>
            <li style={{ textIndent: '0' }}><strong>Mayor motivación:</strong> Ver los progresos constantes ayuda a mantener la motivación y el compromiso a largo plazo con el entrenamiento.</li>
           </ul>
           <p style={{ textIndent: '0' }}>Algunos ejemplos de progresión gradual pueden ser:</p>
           <ul>
            <li style={{ textIndent: '0' }}>Aumentar el peso, las repeticiones o series de un ejercicio de manera semanal o mensual.</li>
            <li style={{ textIndent: '0' }}>Incorporar ejercicios más desafiantes a medida que se domina una técnica.</li>
            <li style={{ textIndent: '0' }}>Incrementar gradualmente la duración o intensidad de las sesiones cardiovasculares.</li>
           </ul>
           <h2 className="subtitleArt">Consistencia en el entrenamiento</h2>
           <p style={{ textIndent: '2em' }}>La constancia es clave en todo proceso de cambio físico. Realiza actividad física al menos 3-4 veces por semana, variando los grupos musculares que trabajas en cada sesión. Esto ayuda a desarrollar una musculatura equilibrada</p>
           <p style={{ textIndent: '2em' }}>Algunos consejos para mantener la consistencia en el entrenamiento son: establecer un horario fijo y respetarlo con disciplina, Planificar por anticipado las sesiones semanales, Encontrar actividades que realmente disfrutes, Buscar apoyo y motivación en amigos, familiares o entrenadores y Celebrar los pequeños logros para mantenerte enfocado.</p>
           <h2 className="subtitleArt">Alimentación alta en proteina para aumentar masa muscular en piernas y glúteos</h2>
           <p style={{ textIndent: '2em' }}>La <a className="linkAbsolute" href="https://www.fitknow.fit/alimentos-altos-en-proteinas">alimentación alta en proteínas</a> es fundamental para aumentar la masa muscular, especialmente en áreas como las piernas y los glúteos. Las proteínas son los bloques constructivos esenciales para el crecimiento y reparación muscular, por lo que un consumo adecuado de proteínas, junto con el entrenamiento, es importante para estimular la síntesis de nuevas fibras musculares. </p>
           <p style={{ textIndent: '2em' }}>Se recomienda consumir entre 1.6 y 2.2 gramos de proteína por kilogramo de peso corporal al día, obtenidas de fuentes como carnes magras, pescado, huevos, lácteos, legumbres, frutos secos y semillas, variando las fuentes para obtener todos los aminoácidos esenciales. Es importante distribuir el consumo de proteínas en varias comidas a lo largo del día, cada 3-4 horas, incluyendo antes y después del entrenamiento, para maximizar la utilización por parte del organismo. </p>
           <p style={{ textIndent: '2em' }}>Los <a className="linkAbsolute" href="https://www.fitknow.fit/recomendacion-creatina-o-proteina">suplementos proteicos</a> como el whey, caseína o proteína de soja también pueden ser útiles para cubrir las necesidades proteicas, especialmente después del entrenamiento. </p>
           <p style={{ textIndent: '2em' }}>Aqui te dejamos <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-desayunos-altos-en-proteina">7 Recetas de desayunos altos en proteína</a> y <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-de-almuerzos-altos-en-proteinas">4 recetas de almuerzos altos en proteínas</a></p>
           <h2 className="subtitleArt">Descanso para aumentar masa muscular en piernas y glúteos</h2>
           <p style={{ textIndent: '2em' }}>El descanso y la recuperación son fundamentales para aumentar la masa muscular en las piernas y glúteos. Es importante tomar períodos de descanso adecuados entre sets, usualmente entre 2-3 minutos, para permitir que los músculos se recuperen y acumulen la energía necesaria para el próximo esfuerzo. Además, se debe dejar al menos 1-2 días de descanso entre sesiones de entrenamiento enfocadas en piernas y glúteos, para permitir que los músculos se reparen y crezcan después del estrés del entrenamiento.</p>
           <p style={{ textIndent: '2em' }}>El sueño reparador, de 7-9 horas de calidad por noche, es importante, ya que durante el sueño el cuerpo libera hormonas anabólicas que estimulan la síntesis de proteínas y el crecimiento muscular.</p>
           <p style={{ textIndent: '2em' }}>Para aumentar la masa muscular en piernas y glúteos, es clave seguir un plan de entrenamiento que incluya ejercicios compuestos, variedad de movimientos, progresión gradual de cargas, calentamiento adecuado, una alimentación rica en proteínas y descansos apropiados. Mantener la consistencia en la aplicación de estos elementos es fundamental para lograr resultados efectivos y a largo plazo de forma segura.</p>
        </div>
    )
} 
export default ArtIdUno