const ArtIdCuatro = () => {

    return(
        <div>
            <h2 className="subtitleArt">Ejercicios de cardio para quemar grasa corporal</h2>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '0'}}><b>Burpees.</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>Uno de los ejercicios estrella para este propósito son los burpees. Se trata del ejercicio por excelencia de múltiples rutinas, incluido el entrenamiento HIIT. Su práctica nos ayuda al propósito de perder peso y reducir la grasa corporal.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Para realizar los burpees, hay que colocarse de pie, con las piernas separadas. En esta posición hay que bajar el cuerpo haciendo una especie de sentadilla y apoyar las manos en el suelo, por delante del pecho. Debemos de estirar las piernas hacia atrás y dejaremos que las puntas de los pies nos sostengan. Flexionamos los codos y llevamos el cuerpo lo más cerca posible al suelo. Estiramos los brazos y doblamos las rodillas para que toquen el pecho. Finalmente, nos levantaremos dando un salto y a por el siguiente.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Con este ejercicio conseguimos que todos nuestros músculos se ejerciten, aunque algunos más que otros, como tríceps, cuádriceps y pectorales.</p>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '0'}}><b>Saltar a la cuerda.</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>Otra actividad que activa muchísimo y quema grasas es saltar a la comba, ya que tiene la implicación de muchos grupos musculares y provoca la activación del cardio, según explican desde la Escuela Europea del Deporte. "Saltar a la cuerda es el ejercicio ideal para quemar calorías y perder peso. En cada brinco que das involucras todos los músculos del cuerpo: piernas, pectorales, hombros, espalda, abdomen, glúteos y brazos", aseguran. "Diez minutos de saltos con cuerda pueden hacer la misma función que 30 minutos de trote seguido".</p>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '0'}}><b>Running.</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>El otro gran aliado para quemar grasa de forma rápida es el running. Según un estudio de la Escuela de Medicina de la Universidad de Harvard, que ha elaborado un listado con la cantidad de calorías que se queman de media en 30 minutos de ejercicio físico en función del tipo elegido y del peso corporal, una persona de unos 70 kilos que corra a un buen ritmo y de forma constante durante 10 minutos puede quemar 223 calorías, y si lo hiciera a una velocidad de unos 8 kilómetros durante 30 minutos la cifra ascendería a 298 calorías.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Un dato más, se pierde más grasa abdominal con las carreras de intervalos -cortas, pero de gran intensidad- que con las de fondo o larga distancia. Tiene una explicación: al correr a distintas velocidades se aumenta el flujo de oxígeno a los músculos, lo que estimula el metabolismo y quema más calorías. "El entrenamiento de alta intensidad que implica un alto nivel de esfuerzo en un periodo corto de tiempo es más efectivo a la hora de quemar grasa, especialmente si es del abdomen", concluyen desde Asics.</p>
            <h2 className="subtitleArt">Ejercicios de fuerza para quemar grasa corporal</h2>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '0'}}><b>Sentadillas.</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>La sentadilla es un movimiento compuesto que involucra múltiples articulaciones y grupos musculares, convirtiéndose en uno de los ejercicios de fuerza más completos y eficientes para la quema de grasa. Al realizar este ejercicio, se activan de manera simultánea los músculos de las piernas, como los cuádriceps, isquiotibiales y glúteos, así como también los músculos del core, estabilizando la columna vertebral y brindando soporte a todo el cuerpo.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Debido a este reclutamiento muscular tan amplio, la sentadilla genera un gasto energético muy elevado, no solo durante la ejecución del ejercicio, sino también en las horas posteriores, gracias al aumento del metabolismo que produce. Este efecto termogénico ayuda a quemar un mayor número de calorías y, por ende, a reducir los depósitos de grasa corporal.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Además de los beneficios metabólicos, la sentadilla también mejora la fuerza, la potencia y la estabilidad de los músculos involucrados. Esto se traduce en una mayor capacidad para realizar actividades de la vida diaria, así como también un aspecto más tonificado y definido de la musculatura.</p>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '0'}}><b>Peso muerto.</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>Al igual que la sentadilla, el peso muerto es un movimiento compuesto que involucra múltiples grupos musculares, lo que lo convierte en un ejercicio sumamente efectivo para la quema de grasa. Durante la ejecución del peso muerto, se activan principalmente los músculos de la espalda, las piernas y el core, generando un gran gasto energético que se traduce en un aumento significativo del metabolismo.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Además de los beneficios metabólicos, el peso muerto también es extremadamente eficaz para <a className="linkAbsolute" href="https://www.fitknow.fit/masa-muscular-en-piernas-y-gluteos">mejorar la fuerza de los músculos implicados</a>. Al cargar con una barra cargada desde el suelo hasta la posición erguida, se desarrolla una gran fortaleza en la zona posterior del cuerpo, lo que se refleja en una mejor postura y una apariencia más tonificada.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Otro aspecto a destacar del peso muerto es su capacidad para mejorar la estabilidad y el control del core. Al mantener una posición neutra de la columna vertebral durante todo el movimiento, se fortalece la musculatura del abdomen y la espalda, lo que se traduce en una mayor capacidad para transferir fuerza a través del cuerpo durante la realización de otras actividades físicas.</p>
            <h3 style={{fontSize: '28px', color: '#374C08', marginBottom: '5px', textIndent: '0'}}><b>Press de hombros.</b></h3>
            <p style={{marginTop: '0', textIndent: '2em'}}>El press de hombros es un movimiento compuesto que principalmente trabaja los músculos deltoides, responsables de la elevación de los brazos. Sin embargo, este ejercicio también involucra otros grupos musculares clave, como los músculos del core, los tríceps y los músculos estabilizadores de la espalda.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Al realizar repeticiones del press de hombros, ya sea con mancuernas, una barra o en posición de pie o sentado, se genera un gasto energético considerable. Esto se debe a que los músculos deltoides son grandes y requieren una gran cantidad de energía para moverse. Además, al mantener una posición estable durante el ejercicio, se activa de forma sostenida la musculatura del core, lo que contribuye aún más a la quema de calorías.</p>
            <p style={{marginTop: '0', textIndent: '2em'}}>Más allá de los beneficios metabólicos, el press de hombros también tiene un impacto positivo en la <a className="linkAbsolute" href="https://www.fitknow.fit/Tips-para-aumentar-masa-muscular">fuerza y la definición muscular</a>. Al trabajar los deltoides, se logra una mejora en la postura y una apariencia más atlética y tonificada en la zona del hombro y la parte superior del cuerpo.</p>
            <h2 className="subtitleArt">Beneficios de incorporar entrenamientos de fuerza para quemar grasa en tu rutina de entrenamiento</h2>
            <ul>
                <li style={{ textIndent: '0' }}><strong> Aumento del Gasto Energético:</strong> Los ejercicios de fuerza requieren una gran demanda metabólica, lo que implica que el cuerpo quema más calorías durante y después de la sesión de entrenamiento. Esto se debe al <a className="linkAbsolute" href="https://www.fitknow.fit/Tips-para-aumentar-masa-muscular">incremento de la masa muscular</a>, la cual requiere más energía para su mantenimiento.</li>
                <li style={{ textIndent: '0' }}><strong>Efecto Termogénico:</strong> El entrenamiento de fuerza estimula la actividad de las hormonas que aceleran el metabolismo, como la testosterona y la hormona del crecimiento. Esto genera un aumento en la tasa metabólica basal, traducido en un mayor gasto calórico en reposo.</li>
                <li style={{ textIndent: '0' }}><strong>Mejora de la Composición Corporal:</strong>Al ganar músculo y perder grasa, se mejora la composición corporal, lo que se traduce en un aspecto más tonificado y saludable.</li>
                <li style={{ textIndent: '0' }}><strong>Mejor control de la técnica:</strong> Entrenar con cargas más livianas facilita mantener una ejecución correcta de los ejercicios, evitando compensaciones que podrían derivar en lesiones a largo plazo.</li>
                <li style={{ textIndent: '0' }}><strong>Mayor sensibilidad a la insulina:</strong> Los ejercicios de fuerza aumentan la captación y utilización de glucosa por parte de los músculos, mejorando la sensibilidad a la insulina. Esto ayuda a regular los niveles de azúcar en sangre y a reducir el almacenamiento de grasa.</li>
                <li style={{ textIndent: '0' }}><strong>Incremento del Metabolismo Mitocondrial:</strong> El entrenamiento de fuerza estimula la biogénesis mitocondrial, es decir, la creación de más mitocondrias en las células. Esto se traduce en una mayor capacidad para quemar grasas y carbohidratos como fuente de energía.</li>
            </ul>
        </div>
    )
}

export default ArtIdCuatro