const ArtIdTres = () => {
    return(
        <div>
            <h2 className="subtitleArt">1. Realizar entrenamiento de fuerza de 3 a 5 veces por semana para aumentar masa muscular</h2>
            <p style={{ textIndent: '2em' }}>El entrenamiento de fuerza es una estrategia clave cuando el objetivo es ganar masa muscular. Este tipo de ejercicios deberían formar parte integral de tu rutina semanal. Se recomienda dedicar entre 3 a 5 sesiones semanales al entrenamiento de fuerza. Esta frecuencia adecuada permitirá estimular eficazmente tus músculos, promoviendo su crecimiento y desarrollo (hipertrofia).</p>
            <p style={{ textIndent: '2em' }}>Es importante encontrar el equilibrio correcto. Entrenar con una frecuencia menor puede limitar los resultados, mientras que excederse aumenta el riesgo de lesiones. La clave está en la consistencia y en respetar los tiempos de recuperación.</p>
            <p style={{ textIndent: '2em' }}>Cada grupo muscular debe ser trabajado de 1 a 2 veces por semana, de manera que tengan el tiempo necesario para repararse y crecer. Este enfoque gradual y balanceado te ayudará a construir masa muscular de forma segura y sostenible.</p>
            <p style={{ textIndent: '2em' }}>Mantén una disciplina inquebrantable en tus entrenamientos de fuerza, pero sin olvidar la importancia del descanso y la recuperación adecuada. Monitorea constantemente cómo tu cuerpo responde y ajusta la rutina según sea necesario. Te invitamos a leer: <a className="linkAbsolute" href="https://www.fitknow.fit/masa-muscular-en-piernas-y-gluteos">Aumentar masa muscular en piernas y glúteos</a></p>
            <h2 className="subtitleArt">2. Comenzar el entrenamiento con ejercicios de musculatura</h2>
            <p style={{ textIndent: '2em' }}>Es importante que el entrenamiento se realice de forma intensa. Se recomienda iniciar con un calentamiento leve, que puede ser a través de ejercicios aeróbicos o por medio de la repetición rápida de un ejercicio de musculación que formará parte del entrenamiento del día.</p>
            <p style={{ textIndent: '2em' }}>Después del entrenamiento de musculación, se recomienda también realizar un entrenamiento aeróbico. Esto ayudará en el proceso de aumento del metabolismo y gasto calórico, favoreciendo así la hipertrofia.</p>
            <p style={{ textIndent: '2em' }}>Comenzar con ejercicios que involucren grandes grupos musculares como sentadillas, hombros, pecho y espalda es ideal. Estos ejercicios compuestos permiten activar múltiples músculos a la vez, lo que maximiza el estímulo y el potencial de crecimiento muscular.</p>
            <p style={{ textIndent: '2em' }}>Una vez finalizada la parte principal de entrenamiento de fuerza, se pueden incluir ejercicios más aislados para grupos musculares específicos. Esto permite enfocarse en desarrollar ciertos músculos de forma más detallada.</p>
            <p style={{ textIndent: '2em' }}>Mantener una intensidad y volumen de entrenamiento adecuados es clave. Asegúrate de emplear cargas pesadas y un número suficiente de series y repeticiones por ejercicio. Esto generará la fatiga muscular necesaria para promover la hipertrofia.</p>
            <h2 className="subtitleArt">3. Realizar cada ejercicio al 65% de la carga máxima para aumentar masa muscular</h2>
            <p style={{ textIndent: '2em' }}>Los ejercicios deben realizarse utilizando alrededor del 65% de la carga máxima que se logra hacer en una sola repetición. Por ejemplo, si se logra hacer solo una repetición de extensión de muslo con 30 kg, para realizar toda la serie del ejercicio, se debe utilizar un peso más o menos de 20 kg. A medida que la persona va realizando el entrenamiento, es normal que esos 20 kg se perciban más leves. Por lo tanto, es necesario que haya un aumento progresivo del peso utilizado. De esta forma, es posible promover de manera más efectiva la hipertrofia.</p>
            <p style={{ textIndent: '0' }}>Realizar los ejercicios al 65% de la carga máxima brinda varios beneficios clave:</p>
            <ul>
                <li style={{ textIndent: '0' }}><strong>Estimulación óptima de la hipertrofia:</strong> Esta intensidad de carga promueve la activación de las fibras musculares de tipo II, que son las más responsables del crecimiento muscular.</li>
                <li style={{ textIndent: '0' }}><strong>Menor riesgo de lesiones:</strong> Trabajar con cargas más moderadas, en comparación a las cargas máximas, reduce significativamente el estrés sobre las articulaciones y tendones, disminuyendo así la probabilidad de lesiones.</li>
                <li style={{ textIndent: '0' }}><strong>Mayor volumen de entrenamiento:</strong>A l poder completar más repeticiones con el 65% de la carga máxima, se logra un mayor volumen de trabajo en cada sesión, lo cual es clave para promover la hipertrofia</li>
                <li style={{ textIndent: '0' }}><strong>Mejor control de la técnica:</strong> Entrenar con cargas más livianas facilita mantener una ejecución correcta de los ejercicios, evitando compensaciones que podrían derivar en lesiones a largo plazo.</li>
                <li style={{ textIndent: '0' }}><strong>Mayor tiempo bajo tensión:</strong> Al poder realizar más repeticiones, los músculos permanecen bajo tensión por más tiempo, lo que también contribuye al estímulo hipertrófico.</li>
            </ul>
            <h2 className="subtitleArt">4. Realizar cada ejercicio lentamente</h2>
            <p style={{ textIndent: '2em' }}>Los ejercicios de musculatura se deben hacer de forma lenta, principalmente durante la fase de contracción del músculo. Esto se debe a que al realizar los movimientos de manera más lenta, un mayor número de fibras musculares se lesionan durante la actividad.</p>
            <p style={{ textIndent: '2em' }}>Como resultado, la ganancia de masa muscular durante el período de recuperación es más efectiva. Además de favorecer la hipertrofia, la realización lenta del movimiento también hace que la persona adquiera una mayor conciencia corporal. Esto ayuda a evitar compensaciones durante el ejercicio, lo cual termina por dificultar</p>
            <h2 className="subtitleArt">5. Ingerir alimentos ricos en proteínas para aumentar masa muscular</h2>
            <p style={{ textIndent: '2em' }}>Para ganar masa muscular, es importante que la persona tenga una alimentación saludable y rica en proteínas. Se recomienda una ingesta entre 1,6 a 1,8 g de proteína por kg de peso al día.Algunos <a className="linkAbsolute" href="https://www.fitknow.fit/recomendacion-creatina-o-proteina">suplementos como las proteínas en polvo, la creatina</a> o la vitamina D pueden ser útiles para complementar una dieta adecuada y estimular el crecimiento muscular. Además, se debe aumentar entre 400 a 500 kcal en la dieta diaria, de manera que se consuman más calorías de las que se gastan. Algunos <a className="linkAbsolute" href="http://localhost:3000/alimentos-altos-en-proteinas">alimentos ricos en proteínas</a> son los huevos, pollo, pescados, carnes rojas, garbanzos, lentejas y soja, por ejemplo. Estos alimentos son importantes para favorecer la hipertrofia muscular, ya que son responsables del mantenimiento de las fibras musculares.</p>
            <p style={{ textIndent: '2em' }}>Aqui te dejamos <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-desayunos-altos-en-proteina">7 Recetas de desayunos altos en proteína</a> y <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-de-almuerzos-altos-en-proteinas">4 recetas de almuerzos altos en proteínas</a></p>
            <h2 className="subtitleArt">6. Dormir bien para aumentar masa muscular</h2>
            <p style={{ textIndent: '2em' }}>El sueño adecuado es fundamental para aumentar la masa muscular de manera efectiva. Dormir bien, es decir, entre 7 a 9 horas por noche, permite que los músculos se recuperen y se fortalezcan después del entrenamiento. Durante el sueño, el cuerpo libera hormonas anabólicas como la hormona del crecimiento y la testosterona, las cuales son cruciales para el proceso de reparación y crecimiento muscular.</p> 
            <p style={{ textIndent: '2em' }}>Asimismo, el sueño ayuda a regular los niveles de cortisol, una hormona catabólica que, en exceso, puede interferir con la síntesis de proteínas y el desarrollo muscular. Además, el descanso adecuado favorece la supercompensación, lo que significa que los músculos se vuelven más fuertes y resistentes después de la actividad física. Por otro lado, la falta de sueño puede aumentar los niveles de estrés, lo que a su vez puede inhibir la recuperación muscular y obstaculizar el proceso de hipertrofia. Por lo tanto, priorizar un buen patrón de sueño, manteniendo horarios de acostarse y despertar consistentes, es fundamental para optimizar el crecimiento muscular y alcanzar los objetivos de entrenamiento.</p>
        </div>
    )
}

export default ArtIdTres