const ArtIdDos = () => {
    return(
        <div>
            <h2 className="subtitleArt">Cómo mantener la fuerza y masa muscular a medida que envejecemos</h2>
            <p style={{ textIndent: '2em' }}>A partir de los 50 años, la fuerza y masa muscular tienden a disminuir gradualmente con el tiempo. Incluso pérdidas moderadas de masa muscular pueden llevar a una importante debilidad, lo que supone un problema para quienes desean mantener un estilo de vida físicamente activo y disfrutar de una buena calidad de vida.</p>
            <p style={{ textIndent: '2em' }}>Los motivos de este deterioro muscular relacionado con la edad son diversos: Niveles reducidos de actividad física, Dieta inadecuada o cambios en el metabolismo proteico de los músculos a lo largo de los años.</p>
            <p style={{ textIndent: '2em' }}>No obstante, esta pérdida de fuerza y masa muscular no tiene por qué ser irreversible. Existen formas de mantener y mejorar la salud y función muscular a medida que envejecemos.</p>
            <h2 className="subtitleArt">La importancia del entrenamiento de fuerza para mantener la salud muscular en la adultez</h2>
            <p style={{ textIndent: '2em' }}>La actividad física es una de las mejores cosas que una persona puede hacer para mejorar su salud. Esto es especialmente importante para aquellas personas que han cumplido los 50 años. Una de las mejores maneras de mantener la salud y la fuerza de los músculos es haciendo ejercicios de entrenamiento de fuerza (también conocidos como entrenamiento de resistencia o levantamiento de pesas).</p>
            <p style={{ textIndent: '2em' }}>Realizados con regularidad, es decir, de 2 a 3 entrenamientos por semana, estos ejercicios ayudan a <a className="linkAbsolute" href="https://www.fitknow.fit/Tips-para-aumentar-masa-muscular">desarrollar la fuerza muscular y la masa muscular </a>, y contribuyen a preservar la densidad ósea, la independencia y la vitalidad con la edad. Idealmente, las actividades de fortalecimiento muscular deberían trabajar todos los principales grupos musculares de nuestro cuerpo (piernas, cadera, espalda, abdomen, tórax, hombros y brazos). Esto puede incluir:</p>
            <ul>
                <li style={{ textIndent: '0' }}>Ejercicios de fuerza utilizando bandas elásticas, máquinas de pesas o mancuernas.</li>
                <li style={{ textIndent: '0' }}>Ejercicios con peso corporal, como flexiones, estiramientos, planchas, sentadillas o zancadas.</li>
                <li style={{ textIndent: '0' }}>Algunas posturas de <a className="linkAbsolute" href="https://www.fitknow.fit/beneficios-del-yoga">yoga.</a></li>
                <li style={{ textIndent: '0' }}>Algunas formas de tai chi.</li>
                <li style={{ textIndent: '0' }}>Actividades como llevar la compra, excavar o elevar peso.</li>
            </ul>
            <p style={{ textIndent: '2em' }}>Dependiendo de tu nivel de forma física, la intensidad de estas actividades puede ser relativamente moderada o relativamente intensa. Es recomendable consultar a tu médico antes de iniciar cualquier rutina de entrenamiento de fuerza.</p>
            <h2 className="subtitleArt">El poder de las proteínas en el desarrollo de masa muscular en la adultez</h2>
            <p style={{ textIndent: '2em' }}>La proteína es el principal componente de los músculos, por lo que este nutriente es especialmente importante para nuestro sistema muscular. Una vez ingerida, nuestro organismo obtiene la proteína de los alimentos y la descompone en aminoácidos, que se utilizan para el desarrollo de los músculos. Sin embargo, a medida que cumplimos años, el metabolismo proteico muscular puede cambiar y, por lo tanto, la capacidad de desarrollar músculo se reduce, un fenómeno denominado resistencia anabólica.</p>
            <p style={{ textIndent: '2em' }}>Por lo tanto, se ha sugerido que los adultos mayores pueden requerir mayores cantidades de proteínas para estimular la síntesis proteica de los músculos y la señalización anabólica en los músculos. Aqui te dejamos <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-desayunos-altos-en-proteina">7 Recetas de desayunos altos en proteína</a> y <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-de-almuerzos-altos-en-proteinas">4 recetas de almuerzos altos en proteínas</a></p>
            <p style={{ textIndent: '2em' }}>Existen varias formas de obtener las proteínas adicionales necesarias. Las fuentes de proteínas animales (carne, pescado, huevos y leche) se consideran la mejor opción, ya que ofrecen las proporciones adecuadas de todos esos aminoácidos, que son necesarios pero que nuestro organismo no puede producir (también conocidos como aminoácidos esenciales). No obstante, siempre es mejor tomar una gran variedad de <a className="linkAbsolute" href="https://www.fitknow.fit/alimentos-altos-en-proteinas">alimentos con proteínas</a> de buena calidad procedentes de carnes magras, o con niveles reducidos de grasas saturadas, como: Pescado o pollo magro, Yogur de leche desnatada, Leche desnatada y lentejas, guisantes o alubias cocidas</p>
            <h2 className="subtitleArt">Calidad del entrenamiento para mantener la masa muscular  después de los 50 años</h2>
            <p style={{ textIndent: '2em' }}>Uno de los puntos clave a la hora de ganar masa muscular después de los 50 años es enfocarse en la calidad del entrenamiento, en lugar de simplemente buscar levantar cargas excesivas. A esta edad, es fundamental realizar los ejercicios con una técnica cuidadosa y un control preciso del movimiento, en vez de caer en la tentación de sacrificar la forma por cargar más peso.</p>
            <p style={{ textIndent: '2em' }}>Esto es crucial para evitar lesiones, que pueden ser más comunes conforme avanzamos en edad. Además, el enfoque en la calidad del movimiento ayudará a estimular de manera más efectiva el crecimiento y la reparación muscular, lo cual es el objetivo principal. Si bien el ego puede tentarnos a querer mover grandes pesos, es mejor dejar el orgullo a un lado y priorizar la ejecución correcta de cada ejercicio. De esta forma, podrás construir músculo de manera segura y sostenible a largo plazo. Recuerda que a esta edad, la paciencia y la perseverancia serán tus mejores aliadas en el camino hacia un físico más fuerte y saludable.</p>
            <h2 className="subtitleArt">Uso de suplementos para ganar masa muscular después de los 50 años</h2>
            <p style={{ textIndent: '2em' }}>En cuanto al uso de suplementos para ganar masa muscular después de los 50 años, es un aspecto que vale la pena considerar con cautela. Algunos <a className="linkAbsolute" href="https://www.fitknow.fit/recomendacion-creatina-o-proteina">suplementos como las proteínas en polvo, la creatina</a> o la vitamina D pueden ser útiles para complementar una dieta adecuada y estimular el crecimiento muscular.</p>
            <p style={{ textIndent: '2em' }}>Sin embargo, es importante tener en cuenta que los suplementos no deben verse como un reemplazo de una alimentación saludable y balanceada. Siguen siendo solo complementos y su efectividad dependerá de una base sólida de entrenamiento y nutrición. Además, a esta edad, es fundamental consultar con un profesional de la salud antes de iniciar cualquier programa de suplementación, ya que pueden existir interacciones o efectos secundarios que deban ser monitoreados, especialmente si se toman medicamentos.</p>
            <p style={{ textIndent: '2em' }}>El uso responsable y con asesoría experta de ciertos suplementos puede ser beneficioso, pero nunca debe ser el único pilar en el que se sustente tu estrategia para ganar masa muscular. Mantén el foco principal en la calidad de tu alimentación, el entrenamiento adecuado y el descanso, y utiliza los suplementos de manera complementaria si tu médico lo considera apropiado. De esta forma, podrás construir músculo de manera segura y saludable.</p>
            <h2 className="subtitleArt">Control del estrés para ganar masa muscular en la adultez</h2>
            <p style={{ textIndent: '2em' }}>Cuando se trata de ganar masa muscular después de los 50 años es importante el control del estrés. Es bien sabido que el estrés elevado puede tener un impacto negativo en el crecimiento y la recuperación muscular, ya que puede inhibir la producción de hormonas anabólicas clave.</p>
            <p style={{ textIndent: '2em' }}>Por lo tanto, como parte de tu estrategia integral para aumentar tu masa muscular, es fundamental que prestes especial atención a las técnicas que te ayuden a gestionar y reducir los niveles de estrés. Actividades como la práctica regular de yoga, la meditación o simplemente reservar tiempo para actividades relajantes y placenteras pueden ser de gran ayuda.</p>
            <p style={{ textIndent: '2em' }}>Recuerda que a esta edad, el estrés puede manifestarse de diversas formas, tanto física como mentalmente. Es importante que seas consciente de tus niveles de estrés y que busques formas saludables de gestionarlo. Esto no solo beneficiará tu proceso de construcción muscular, sino que también contribuirá a tu bienestar general y a una mejor calidad de vida.</p>
            <p style={{ textIndent: '2em' }}>No subestimes el poder que tiene el manejo adecuado del estrés en tu objetivo de ganar masa muscular. Dedica el tiempo y los esfuerzos necesarios para encontrar las herramientas y estrategias que funcionen mejor para ti. Tu cuerpo y tu mente te lo agradecerán.</p>
        </div>
    )
}

export default ArtIdDos