const ArtIdQuince = () => {
    const arr = ["1. Proteína de suero en polvo: 80g","2. Lomo embuchado: 50g","3. Atún en lata: 32g","4. Pechuga de pollo: 31g", "5. Lomo de cerdo: 30g","6. Filete de ternera: 29g","7. Queso parmesano: 28g","8. Salchichón: 28g","9. Chorizo: 27g","10. Lentejas: 26g","11. Almendras: 21g","12. Sardinas: 21g","13. Garbanzos: 21g","14. Atún fresco: 21g","15. Soja: 20g","16. Pistachos: 20g","17. Merluza: 19g","18. Tofu: 17g","19. Salmón: 17g","20. Anchoas: 17g","21. Trucha: 17g","22. Yogur natural: 16g","23. Queso mozzarella: 16g","24. Nueces: 15g","25. Jamón serrano: 15g","26. Huevos: 13g","27. Calamares: 13g","28. Queso cheddar: 13g","29. Leche entera: 12g","30. Langostinos: 12g","31. Mejillones: 12g","32. Queso roquefort: 11g","33. Brócoli: 11g","34. Leche de soja: 10g","35. Espinacas: 6g","36. Guisantes: 6g","37. Leche de almendras: 5g"]

    return(
        <div>
            <h2 className="subtitleArt">Alimentos altos en Proteínas (expresado en g por cada 100g de porción comestible)</h2>
            {arr.map((item) => (
                <h3 style={{ textIndent: '2em' }} key={item}>{item}</h3>
            ))}
            <p style={{ textIndent: '2em' }}>Aqui te dejamos <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-desayunos-altos-en-proteina">7 Recetas de desayunos altos en proteína</a> y <a className="linkAbsolute" href="https://www.fitknow.fit/recetas-de-almuerzos-altos-en-proteinas">4 recetas de almuerzos altos en proteínas</a></p>
            <h2 className="subtitleArt">Importancia del consumo de proteínas en tu dieta diaria</h2>
            <p style={{ textIndent: '2em' }}>La proteína es un macronutriente esencial para el funcionamiento adecuado de nuestro organismo. Desempeña roles fundamentales en múltiples procesos fisiológicos, por lo que su consumo regular y suficiente es de gran importancia para mantener una salud óptima.</p>
            <p style={{ textIndent: '2em' }}>En primer lugar, la proteína es el principal componente estructural de nuestras células, tejidos y órganos. Forma parte de músculos, huesos, piel, cabello, uñas y prácticamente todas las estructuras del cuerpo. Sin una ingesta adecuada de proteínas, no podríamos mantener la integridad y funcionamiento de estos tejidos, lo que conlleva a debilidad muscular, fragilidad ósea, problemas dermatológicos, caída del cabello y otras consecuencias negativas.</p>
            <p style={{ textIndent: '2em' }}>Además, las <a className="linkAbsolute" href="https://www.fitknow.fit/aumentar-la-hemoglobina">proteínas son cruciales para el sistema inmunológico</a>, ya que son los principales componentes de anticuerpos y células inmunitarias que nos defienden de enfermedades e infecciones. Una dieta insuficiente en proteínas debilita nuestra capacidad de respuesta y resistencia a patógenos.</p>
            <p style={{ textIndent: '2em' }}>Por otra parte, las proteínas juegan un papel clave en el transporte y regulación de diversas sustancias en el organismo, como hormonas, enzimas y neurotransmisores. Esto les confiere un rol fundamental en el control metabólico, la producción energética, la función cerebral y el equilibrio hormonal.</p>
            <p style={{ textIndent: '2em' }}>Finalmente, la proteína es esencial para la reparación y renovación de tejidos dañados. Después de lesiones, cirugías o enfermedades, nuestro cuerpo necesita un aporte adecuado de aminoácidos provenientes de las proteínas para poder regenerar y cicatrizar de manera eficiente.</p>
            <h2 className="subtitleArt">Consecuencias de un consumo bajo de proteínas en tu dieta </h2>
            <p style={{ textIndent: '2em' }}>La falta de una ingesta adecuada de proteínas puede tener consecuencias negativas importantes para la salud y el bienestar general de una persona. Cuando no se consume la cantidad suficiente de este macronutriente esencial, el organismo comienza a experimentar diversos problemas que pueden ser bastante serios si se prolongan en el tiempo.</p>
            <p style={{ textIndent: '2em' }}>En primer lugar, una deficiencia proteica afecta seriamente la composición y función muscular. Sin los bloques constructivos necesarios, la masa y fuerza muscular empiezan a disminuir progresivamente. Esto conlleva a una mayor debilidad y fatiga, lo que dificulta realizar actividades físicas cotidianas. Además, la pérdida de músculo también impacta negativamente en el metabolismo, disminuyendo la capacidad de quemar calorías y aumentando el riesgo de ganar peso.</p>
            <p style={{ textIndent: '2em' }}>Asimismo, la insuficiencia de proteínas compromete la integridad y renovación de otros tejidos clave, como los huesos, la piel, el cabello y las uñas. Sin los nutrientes necesarios, estos tejidos se vuelven más frágiles, propensos a lesiones y problemas, como osteoporosis, problemas dermatológicos y caída excesiva del cabello.</p>
            <p style={{ textIndent: '2em' }}>Por otro lado, la falta de proteínas afecta gravemente al sistema inmunológico. Las células y anticuerpos encargados de defendernos de infecciones y enfermedades dependen de un adecuado aporte de aminoácidos para mantenerse saludables y funcionales. Como resultado, las personas con deficiencia proteica suelen ser más susceptibles a contraer diversas patologías.</p>
            <p style={{ textIndent: '2em' }}>Incluso la función cerebral y el estado de ánimo pueden verse afectados por una ingesta insuficiente de proteínas. Algunos neurotransmisores y hormonas esenciales para la cognición y el equilibrio emocional requieren de estos nutrientes para su síntesis y regulación adecuada.</p>
            <p style={{ textIndent: '2em' }}>Finalmente, la deficiencia proteica puede generar problemas de cicatrización y reparación de tejidos dañados. Después de lesiones, cirugías o enfermedades, el organismo necesita un aporte extra de proteínas para poder reconstruir y regenerar las estructuras afectadas de manera eficiente.</p>
            <h2 className="subtitleArt">Cuánta proteína debemos consumir y beneficios del consumo adecuado de proteínas en tu dieta</h2>
            <p style={{ textIndent: '2em' }}>La cantidad de proteína que una persona debería consumir diariamente varía según diversos factores como la edad, el sexo, el nivel de actividad física y el estado de salud. Sin embargo, las recomendaciones generales indican que la mayoría de los adultos saludables deberían ingerir entre 0.8 y 1.2 gramos de proteína por kilogramo de peso corporal al día.</p>
            <p style={{ textIndent: '2em' }}>Por ejemplo, una persona que pese 70 kilogramos debería consumir entre 56 y 84 gramos de proteína diariamente para satisfacer sus necesidades nutricionales. Estos requerimientos aumentan para personas físicamente activas, en etapas de crecimiento o con objetivos específicos de salud y fitness.</p>
            <p style={{ textIndent: '2em' }}>Cumplir con estas pautas de consumo proteico conlleva múltiples beneficios para la salud y el bienestar. En primer lugar, una ingesta adecuada de proteínas asegura el mantenimiento y desarrollo óptimo de la masa y función muscular. Esto es de suma importancia no sólo para atletas y fisicoculturistas, sino también para <a className="linkAbsolute" href="https://www.fitknow.fit/adquirir-masa-muscular-a-los-50">adultos mayores que buscan preservar su fuerza</a> y movilidad.</p>
            <p style={{ textIndent: '2em' }}>Además, las proteínas juegan un rol fundamental en el fortalecimiento del sistema inmunológico. Los anticuerpos y células de defensa dependen de un aporte suficiente de aminoácidos para poder sintetizar y funcionar de manera efectiva. Esto ayuda a prevenir infecciones y enfermedades, mejorando la resistencia general del organismo.</p>
            <p style={{ textIndent: '2em' }}>Por otra parte, las proteínas son esenciales para la reparación y renovación de tejidos dañados. Después de lesiones, cirugías o enfermedades, el cuerpo necesita nutrirse adecuadamente de estos nutrientes para poder cicatrizar y regenerar las estructuras afectadas.</p>
            <p style={{ textIndent: '2em' }}>Asimismo, el consumo proteico contribuye al equilibrio metabólico y hormonal. Algunos aminoácidos participan en la síntesis y regulación de hormonas clave, como la insulina, la testosterona y los estrógenos. Esto repercute positivamente en el <a className="linkAbsolute" href="https://www.fitknow.fit/ejercicios-para-perder-grasa">control del peso</a>, el rendimiento físico y el estado de ánimo.</p>
            <p style={{ textIndent: '2em' }}>Finalmente, las proteínas son fundamentales para el óptimo funcionamiento cerebral. Intervienen en la producción de neurotransmisores y en procesos como la cognición, la memoria y el estado de alerta. De esta manera, contribuyen a mantener una salud mental saludable y un adecuado rendimiento intelectual.Algunos <a className="linkAbsolute" href="https://www.fitknow.fit/recomendacion-creatina-o-proteina">suplementos como las proteínas en polvo, la creatina</a> o la vitamina D pueden ser útiles para complementar una dieta adecuada y estimular el crecimiento muscular.</p>
            <p style={{ textIndent: '2em', marginTop: '4em' }}>Consumir la cantidad de proteínas recomendada diariamente, entre 0.8 y 1.2 gramos por kilogramo de peso, aporta múltiples beneficios para la composición corporal, la función inmune, la reparación tisular, el equilibrio metabólico y la salud cerebral. Es un nutriente esencial que no debe faltar en una dieta balanceada.</p>
        </div>
    )

}

export default ArtIdQuince

